name: Trigger CodeBuild on PR

on:
  pull_request:
    branches:
      - main
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger AWS CodeBuild
      uses: aws-actions/aws-codebuild-run-build@v1
      with:
        project-name: Testing
        source-version: ${{ github.event.pull_request.head.sha }}
      env:
        AWS_REGION: us-east-1
        AWS_ACCOUNT_ID: 905418283326
